package com.zhongteng.cunren.repository;

import com.zhongteng.cunren.dto.RoleAuth;
import com.zhongteng.cunren.dto.RoleAuthExample;
import com.zhongteng.cunren.dto.RoleAuthKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RoleAuthMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_auth
     *
     * @mbggenerated Wed Mar 29 18:36:59 CST 2017
     */
    int countByExample(RoleAuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_auth
     *
     * @mbggenerated Wed Mar 29 18:36:59 CST 2017
     */
    int deleteByExample(RoleAuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_auth
     *
     * @mbggenerated Wed Mar 29 18:36:59 CST 2017
     */
    int deleteByPrimaryKey(RoleAuthKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_auth
     *
     * @mbggenerated Wed Mar 29 18:36:59 CST 2017
     */
    int insert(RoleAuth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_auth
     *
     * @mbggenerated Wed Mar 29 18:36:59 CST 2017
     */
    int insertSelective(RoleAuth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_auth
     *
     * @mbggenerated Wed Mar 29 18:36:59 CST 2017
     */
    List<RoleAuth> selectByExample(RoleAuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_auth
     *
     * @mbggenerated Wed Mar 29 18:36:59 CST 2017
     */
    RoleAuth selectByPrimaryKey(RoleAuthKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_auth
     *
     * @mbggenerated Wed Mar 29 18:36:59 CST 2017
     */
    int updateByExampleSelective(@Param("record") RoleAuth record, @Param("example") RoleAuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_auth
     *
     * @mbggenerated Wed Mar 29 18:36:59 CST 2017
     */
    int updateByExample(@Param("record") RoleAuth record, @Param("example") RoleAuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_auth
     *
     * @mbggenerated Wed Mar 29 18:36:59 CST 2017
     */
    int updateByPrimaryKeySelective(RoleAuth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_auth
     *
     * @mbggenerated Wed Mar 29 18:36:59 CST 2017
     */
    int updateByPrimaryKey(RoleAuth record);
}