package com.zhongteng.cunren.dto;

public class Area {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_area.id
     *
     * @mbggenerated Wed Mar 29 18:36:59 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_area.area
     *
     * @mbggenerated Wed Mar 29 18:36:59 CST 2017
     */
    private String area;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_area.parentId
     *
     * @mbggenerated Wed Mar 29 18:36:59 CST 2017
     */
    private Integer parentid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_area.comment
     *
     * @mbggenerated Wed Mar 29 18:36:59 CST 2017
     */
    private String comment;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_area.id
     *
     * @return the value of t_area.id
     *
     * @mbggenerated Wed Mar 29 18:36:59 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_area.id
     *
     * @param id the value for t_area.id
     *
     * @mbggenerated Wed Mar 29 18:36:59 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_area.area
     *
     * @return the value of t_area.area
     *
     * @mbggenerated Wed Mar 29 18:36:59 CST 2017
     */
    public String getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_area.area
     *
     * @param area the value for t_area.area
     *
     * @mbggenerated Wed Mar 29 18:36:59 CST 2017
     */
    public void setArea(String area) {
        this.area = area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_area.parentId
     *
     * @return the value of t_area.parentId
     *
     * @mbggenerated Wed Mar 29 18:36:59 CST 2017
     */
    public Integer getParentid() {
        return parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_area.parentId
     *
     * @param parentid the value for t_area.parentId
     *
     * @mbggenerated Wed Mar 29 18:36:59 CST 2017
     */
    public void setParentid(Integer parentid) {
        this.parentid = parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_area.comment
     *
     * @return the value of t_area.comment
     *
     * @mbggenerated Wed Mar 29 18:36:59 CST 2017
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_area.comment
     *
     * @param comment the value for t_area.comment
     *
     * @mbggenerated Wed Mar 29 18:36:59 CST 2017
     */
    public void setComment(String comment) {
        this.comment = comment;
    }
}