package com.zhongteng.cunren.dto;

import java.util.Date;

public class Auth {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_auth.id
     *
     * @mbggenerated Wed Mar 29 18:36:59 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_auth.auth_type
     *
     * @mbggenerated Wed Mar 29 18:36:59 CST 2017
     */
    private Byte authType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_auth.name
     *
     * @mbggenerated Wed Mar 29 18:36:59 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_auth.url
     *
     * @mbggenerated Wed Mar 29 18:36:59 CST 2017
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_auth.param
     *
     * @mbggenerated Wed Mar 29 18:36:59 CST 2017
     */
    private String param;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_auth.access_type
     *
     * @mbggenerated Wed Mar 29 18:36:59 CST 2017
     */
    private Byte accessType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_auth.sort_id
     *
     * @mbggenerated Wed Mar 29 18:36:59 CST 2017
     */
    private Integer sortId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_auth.pid
     *
     * @mbggenerated Wed Mar 29 18:36:59 CST 2017
     */
    private String pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_auth.create_user_id
     *
     * @mbggenerated Wed Mar 29 18:36:59 CST 2017
     */
    private String createUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_auth.update_user_id
     *
     * @mbggenerated Wed Mar 29 18:36:59 CST 2017
     */
    private String updateUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_auth.create_date
     *
     * @mbggenerated Wed Mar 29 18:36:59 CST 2017
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_auth.update_date
     *
     * @mbggenerated Wed Mar 29 18:36:59 CST 2017
     */
    private Date updateDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_auth.id
     *
     * @return the value of t_auth.id
     *
     * @mbggenerated Wed Mar 29 18:36:59 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_auth.id
     *
     * @param id the value for t_auth.id
     *
     * @mbggenerated Wed Mar 29 18:36:59 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_auth.auth_type
     *
     * @return the value of t_auth.auth_type
     *
     * @mbggenerated Wed Mar 29 18:36:59 CST 2017
     */
    public Byte getAuthType() {
        return authType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_auth.auth_type
     *
     * @param authType the value for t_auth.auth_type
     *
     * @mbggenerated Wed Mar 29 18:36:59 CST 2017
     */
    public void setAuthType(Byte authType) {
        this.authType = authType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_auth.name
     *
     * @return the value of t_auth.name
     *
     * @mbggenerated Wed Mar 29 18:36:59 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_auth.name
     *
     * @param name the value for t_auth.name
     *
     * @mbggenerated Wed Mar 29 18:36:59 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_auth.url
     *
     * @return the value of t_auth.url
     *
     * @mbggenerated Wed Mar 29 18:36:59 CST 2017
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_auth.url
     *
     * @param url the value for t_auth.url
     *
     * @mbggenerated Wed Mar 29 18:36:59 CST 2017
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_auth.param
     *
     * @return the value of t_auth.param
     *
     * @mbggenerated Wed Mar 29 18:36:59 CST 2017
     */
    public String getParam() {
        return param;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_auth.param
     *
     * @param param the value for t_auth.param
     *
     * @mbggenerated Wed Mar 29 18:36:59 CST 2017
     */
    public void setParam(String param) {
        this.param = param;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_auth.access_type
     *
     * @return the value of t_auth.access_type
     *
     * @mbggenerated Wed Mar 29 18:36:59 CST 2017
     */
    public Byte getAccessType() {
        return accessType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_auth.access_type
     *
     * @param accessType the value for t_auth.access_type
     *
     * @mbggenerated Wed Mar 29 18:36:59 CST 2017
     */
    public void setAccessType(Byte accessType) {
        this.accessType = accessType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_auth.sort_id
     *
     * @return the value of t_auth.sort_id
     *
     * @mbggenerated Wed Mar 29 18:36:59 CST 2017
     */
    public Integer getSortId() {
        return sortId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_auth.sort_id
     *
     * @param sortId the value for t_auth.sort_id
     *
     * @mbggenerated Wed Mar 29 18:36:59 CST 2017
     */
    public void setSortId(Integer sortId) {
        this.sortId = sortId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_auth.pid
     *
     * @return the value of t_auth.pid
     *
     * @mbggenerated Wed Mar 29 18:36:59 CST 2017
     */
    public String getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_auth.pid
     *
     * @param pid the value for t_auth.pid
     *
     * @mbggenerated Wed Mar 29 18:36:59 CST 2017
     */
    public void setPid(String pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_auth.create_user_id
     *
     * @return the value of t_auth.create_user_id
     *
     * @mbggenerated Wed Mar 29 18:36:59 CST 2017
     */
    public String getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_auth.create_user_id
     *
     * @param createUserId the value for t_auth.create_user_id
     *
     * @mbggenerated Wed Mar 29 18:36:59 CST 2017
     */
    public void setCreateUserId(String createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_auth.update_user_id
     *
     * @return the value of t_auth.update_user_id
     *
     * @mbggenerated Wed Mar 29 18:36:59 CST 2017
     */
    public String getUpdateUserId() {
        return updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_auth.update_user_id
     *
     * @param updateUserId the value for t_auth.update_user_id
     *
     * @mbggenerated Wed Mar 29 18:36:59 CST 2017
     */
    public void setUpdateUserId(String updateUserId) {
        this.updateUserId = updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_auth.create_date
     *
     * @return the value of t_auth.create_date
     *
     * @mbggenerated Wed Mar 29 18:36:59 CST 2017
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_auth.create_date
     *
     * @param createDate the value for t_auth.create_date
     *
     * @mbggenerated Wed Mar 29 18:36:59 CST 2017
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_auth.update_date
     *
     * @return the value of t_auth.update_date
     *
     * @mbggenerated Wed Mar 29 18:36:59 CST 2017
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_auth.update_date
     *
     * @param updateDate the value for t_auth.update_date
     *
     * @mbggenerated Wed Mar 29 18:36:59 CST 2017
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
}