package com.zhongteng.cunren.dto;

import java.util.Date;

public class Role {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role.id
     *
     * @mbggenerated Wed Mar 29 18:36:59 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role.name
     *
     * @mbggenerated Wed Mar 29 18:36:59 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role.create_user_id
     *
     * @mbggenerated Wed Mar 29 18:36:59 CST 2017
     */
    private String createUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role.update_user_id
     *
     * @mbggenerated Wed Mar 29 18:36:59 CST 2017
     */
    private String updateUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role.create_date
     *
     * @mbggenerated Wed Mar 29 18:36:59 CST 2017
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role.update_date
     *
     * @mbggenerated Wed Mar 29 18:36:59 CST 2017
     */
    private Date updateDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role.id
     *
     * @return the value of t_role.id
     *
     * @mbggenerated Wed Mar 29 18:36:59 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role.id
     *
     * @param id the value for t_role.id
     *
     * @mbggenerated Wed Mar 29 18:36:59 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role.name
     *
     * @return the value of t_role.name
     *
     * @mbggenerated Wed Mar 29 18:36:59 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role.name
     *
     * @param name the value for t_role.name
     *
     * @mbggenerated Wed Mar 29 18:36:59 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role.create_user_id
     *
     * @return the value of t_role.create_user_id
     *
     * @mbggenerated Wed Mar 29 18:36:59 CST 2017
     */
    public String getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role.create_user_id
     *
     * @param createUserId the value for t_role.create_user_id
     *
     * @mbggenerated Wed Mar 29 18:36:59 CST 2017
     */
    public void setCreateUserId(String createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role.update_user_id
     *
     * @return the value of t_role.update_user_id
     *
     * @mbggenerated Wed Mar 29 18:36:59 CST 2017
     */
    public String getUpdateUserId() {
        return updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role.update_user_id
     *
     * @param updateUserId the value for t_role.update_user_id
     *
     * @mbggenerated Wed Mar 29 18:36:59 CST 2017
     */
    public void setUpdateUserId(String updateUserId) {
        this.updateUserId = updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role.create_date
     *
     * @return the value of t_role.create_date
     *
     * @mbggenerated Wed Mar 29 18:36:59 CST 2017
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role.create_date
     *
     * @param createDate the value for t_role.create_date
     *
     * @mbggenerated Wed Mar 29 18:36:59 CST 2017
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role.update_date
     *
     * @return the value of t_role.update_date
     *
     * @mbggenerated Wed Mar 29 18:36:59 CST 2017
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role.update_date
     *
     * @param updateDate the value for t_role.update_date
     *
     * @mbggenerated Wed Mar 29 18:36:59 CST 2017
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
}