package com.zhongteng.cunren.dto;

public class RoleAuthKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role_auth.role_id
     *
     * @mbggenerated Wed Mar 29 18:36:59 CST 2017
     */
    private String roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role_auth.auth_id
     *
     * @mbggenerated Wed Mar 29 18:36:59 CST 2017
     */
    private String authId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role_auth.role_id
     *
     * @return the value of t_role_auth.role_id
     *
     * @mbggenerated Wed Mar 29 18:36:59 CST 2017
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role_auth.role_id
     *
     * @param roleId the value for t_role_auth.role_id
     *
     * @mbggenerated Wed Mar 29 18:36:59 CST 2017
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role_auth.auth_id
     *
     * @return the value of t_role_auth.auth_id
     *
     * @mbggenerated Wed Mar 29 18:36:59 CST 2017
     */
    public String getAuthId() {
        return authId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role_auth.auth_id
     *
     * @param authId the value for t_role_auth.auth_id
     *
     * @mbggenerated Wed Mar 29 18:36:59 CST 2017
     */
    public void setAuthId(String authId) {
        this.authId = authId;
    }
}